# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(containerRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'build'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: 'export'
    - task: AzureFileCopy@3
      inputs:
        SourcePath: '/out'
        azureSubscription: '$(azureSubscription)'
        Destination: 'AzureBlob'
        storage: '$(storageAccount)'
        ContainerName: '$web'