# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Cineplex Hosting(00bf9f5a-77cd-471b-aa9d-d9ef69b8a76f)'
        azureContainerRegistry: '{"loginServer":"cineplex.azurecr.io", "id" : "/subscriptions/00bf9f5a-77cd-471b-aa9d-d9ef69b8a76f/resourceGroups/cineplex-hosting-linux/providers/Microsoft.ContainerRegistry/registries/cineplex"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'